Please add Jakarta EE Specifications Meetings Calendar to the connect…
jakartaee/jakarta.ee pull request #1117
Opened 2021-04-14 17:59 UTC by autumnfound

Closes #1114

2021-04-14 19:57 UTC, chrisguindon approved these changes

2021-04-20 07:06 UTC, ivargrimstad requested changes
See comments.

2021-04-20 07:06 UTC, ivargrimstad commented on i18n/en.toml
> +  other = "LOREM IPSUM."
Change "LOREM IPSUM"  to "Public calendar for all Jakarta EE specification projects.

2021-04-20 07:06 UTC, ivargrimstad commented on i18n/en.toml
> +  other = "Jakarta EE Specifications Meetings Calendar"
Remove "Meetings", so the text is "Jakarta EE Specifications Calendar"

2021-04-29 06:49 UTC, ivargrimstad reviewed
Can we group the spec calendar together with the community calendar? 
Or place it directly below?

2021-04-29 12:54 UTC, TanjaObradovic commented
Maybe we can have a section Jakarta EE Calendars, and underneath Jakarta EE Community Calendar and  Jakarta EE Specifications Meetings Calendar; similar to what we have for Mailing Lists

2021-05-14 15:17 UTC, TanjaObradovic commented
@autumnfound  do you want me to open another issue to group the Calendars? as per my comment above?

2021-05-14 15:30 UTC, autumnfound commented
> @autumnfound do you want me to open another issue to group the Calendars? as per my comment above?

See https://deploy-preview-1117--jakartaee.netlify.app/connect/, I've made an update to lump them together!

2021-05-14 15:36 UTC, TanjaObradovic commented
You are the best! thanks @autumnfound! Looks great!

2021-05-18 17:02 UTC, autumnfound commented
> You are the best! thanks @autumnfound! Looks great!
> 
> The buttons are different under the Calendars, both can say "subscribe"

@TanjaObradovic change is done, just waiting on reviews for this and then I can merge it!

2021-06-03 05:59 UTC, ivargrimstad approved these changes
Looks great! Thanks!

2021-06-03 12:30 UTC, merged