Please update the latest Payara versions on the compatibility page #1203
jakartaee/jakarta.ee pull request #1210
Opened 2021-05-28 19:56 UTC by autumnfound

Fixes #1203

2021-05-31 19:07 UTC, lprimak commented
Hi, @autumnfound 
Thank you for looking at this issue.
However, the latest versions are 5.2021.3 (Community) and 5.28.0 (Enterprise)
Can you reflect those on the page please as opposed to the older versions in this PR?

Thank you!

2021-05-31 19:09 UTC, lprimak requested changes
Please add Community 5.2021.4 as a compatible version as well,
https://www.payara.fish/downloads/payara-platform-community-edition/
thank you!

2021-05-31 19:09 UTC, lprimak commented on data/compatible_products.yml
> +        - version: 5.26.0
Should be 5.28.0

2021-05-31 19:09 UTC, lprimak commented on data/compatible_products.yml
> +        - version: 5.26.0
Should be 5.28.0

2021-05-31 19:53 UTC, autumnfound commented
@lprimak your comments reflect new versions that are not yet validated as certified, and is different than the versions originally requested. We can convert this to draft and wait until the new certification request is finalized, and then update the links accordingly. Does that work with you?

2021-05-31 21:42 UTC, lprimak commented
@autumnfound Yes, Draft sounds good.
See https://github.com/eclipse-ee4j/jakartaee-platform/issues/369
The next versions to be certified would be 5.28.1 and 5.2021.4

Thank you!

2021-06-07 00:12 UTC, lprimak commented
Hi, @autumnfound 
I *believe* the above releases are now Jakarta EE certified

Thank you!

2021-06-07 13:43 UTC, autumnfound commented
@ivargrimstad can you confirm? Its not closed but its got the accepted tag

2021-06-09 19:55 UTC, autumnfound commented
@ivargrimstad @TanjaObradovic So this update would push 2 different product streams under the same product. How do we want to handle this in the UI? 2 separate entries for Payara server, or 2 versions under the same product? I've gone the second for now as it is the most conservative option, and I'm not sure what the procedure is here.

2021-06-10 06:14 UTC, ivargrimstad commented
> @ivargrimstad @TanjaObradovic So this update would push 2 different product streams under the same product. How do we want to handle this in the UI? 2 separate entries for Payara server, or 2 versions under the same product? I've gone the second for now as it is the most conservative option, and I'm not sure what the procedure is here.

I think we should ask Payara for input on whether they see the Payara Server Enterprise and Payara Server Community editions as different versions of the same product, or as distinct products. 
If they are different products, they should be listed separately, similar to e.g. JBoss AS and WildFly. The only difference here is that the products have the same logo, but different names/versions.

2021-06-10 17:42 UTC, lprimak commented
@ivargrimstad @TanjaObradovic @autumnfound 
Hi,
We had an internal discussion here at Payara, and we agree that we want Payara Enterprise and Community to be separate products on the Eclipse Compatibility page.

Can we make that happen? Thank you so much!

2021-06-10 17:44 UTC, lprimak commented
@autumnfound I would also remove the older versions of Payara from the page, I don't believe there is a need to keep them. Just the latest versions.

2021-06-11 16:23 UTC, lprimak approved these changes

2021-06-11 16:23 UTC, lprimak commented
Perfect! Thank you @autumnfound

2021-06-11 17:38 UTC, chrisguindon approved these changes

2021-06-11 17:51 UTC, merged

2021-06-13 08:13 UTC, TanjaObradovic commented
having Payara Enterprise and Community to be separate products on the Eclipse Compatibility page, makes perfect sense to me.

@autumnfound please let us know if you need any other details regarding this.