Fix mobile menu
jakartaee/jakarta.ee pull request #1274
Opened 2021-10-04 15:25 UTC by ericpoirier

Signed-off-by: Eric Poirier <eric.poirier@eclipse-foundation.org>

2021-10-04 19:07 UTC, autumnfound commented on less/components/menu.less
> +        .dropdown-menu {
We can probably combine this line with the previous as there is no classes that target the main-menu other than the ones under dropdown-menu.

2021-10-04 19:08 UTC, autumnfound requested changes
The menu breaks when the page is resized after load.

Additionally, I'm not a fan of breaking the mobile first design, but I understand the reasoning here. It would have been an absolute bear to update all of the rules within the current structure, even if it would have been cleaner.

2021-10-05 12:50 UTC, ericpoirier commented
> The menu breaks when the page is resized after load.

It was breaking because of the match height that was implemented for desktop view.

I'm removing the match height now if the screen is small then 768px which resolves the issue.

> 
> Additionally, I'm not a fan of breaking the mobile first design, but I understand the reasoning here. It would have been an absolute bear to update all of the rules within the current structure, even if it would have been cleaner.

2021-10-05 19:09 UTC, autumnfound approved these changes

2021-10-05 19:11 UTC, linkfang approved these changes

2021-10-05 19:12 UTC, merged