Added Jakarta EE 9 Specifications image
jakartaee/jakarta.ee pull request #1360
Opened 2021-12-15 15:40 UTC by linkfang

Fixes https://github.com/jakartaee/jakarta.ee/issues/1358

2021-12-17 18:07 UTC, chrisguindon requested changes
We need a better solution than linking to xd, I propose that we host the image on jakarta.ee.

2022-01-04 13:25 UTC, ericpoirier commented
@chrisguindon I accidently clicked on re-review but @linkfang still need to change the image urls, no need to re-review now.

2022-01-05 14:20 UTC, linkfang commented
@ericpoirier ,  @chrisguindon I updated the images and changed the urls

2022-01-06 15:02 UTC, ericpoirier approved these changes

2022-01-06 15:03 UTC, merged