Add AISWare Flying Server Compatibility certification
jakartaee/jakarta.ee pull request #1471
Opened 2022-05-12 12:57 UTC by ericpoirier

Fixes #1470

Signed-off-by: Eric Poirier <eric.poirier@eclipse-foundation.org>

2022-05-12 15:37 UTC, ericpoirier commented
We have  the +1 from Tanja.

2022-05-16 14:59 UTC, linkfang requested changes
LGTM! But as the issue creator mentioned in the issue https://github.com/jakartaee/jakarta.ee/issues/1470#issuecomment-1125605258, he updated the logo and will update the download link. So, I think we will need to wait for his update before merging.

2022-05-16 15:01 UTC, ericpoirier commented
> LGTM! But as the issue creator mentioned in the issue [#1470 (comment)](https://github.com/jakartaee/jakarta.ee/issues/1470#issuecomment-1125605258), he updated the logo and will update the download link. So, I think we will need to wait for his update before merging.

Yes, thanks for clarifying this on the PR. I was waiting for the updated link to update this PR.

2022-05-17 12:35 UTC, ericpoirier commented
The logo and link has been updated.

We can review and merge now.

2022-05-17 12:58 UTC, linkfang commented
Cool! But found another small issue. The 2.0.0 link under Download Compatible Products - Jakarta 8 will download a Jakarta zip file instead of the product itself. Most items under 9.1 will download the product directly or take users to the download page. Like,  Eclipse GlassFish and Apusic AAS etc.

2022-05-17 13:00 UTC, linkfang commented on data/compatible_products.yml
> +          download_url: 'http://download.eclipse.org/jakartaee/platform/8/eclipse-jakartaeetck-8.0.2.zip'
I think this is causing the issue I talked about. Looks like a lot of items here under 8.0 are using the same url for both compatibility and download_url. But I think the download_url should be the same as the one for download?

2022-05-17 13:02 UTC, linkfang commented on data/compatible_products.yml
> +          download_url: 'http://download.eclipse.org/jakartaee/platform/8/eclipse-jakartaeetck-8.0.2.zip'
And the compatibility should be link to the tck result link?

2022-05-17 13:32 UTC, ericpoirier commented on data/compatible_products.yml
> +          download_url: 'http://download.eclipse.org/jakartaee/platform/8/eclipse-jakartaeetck-8.0.2.zip'
The Compatibility link should go to the TCK results page which is:

https://github.com/AsiainfoAnhui/aisware_flyingserver_v2_ee8/blob/master/aisware_flyingserver_v2_ee8.md#tck-results

But as for the download_url link, there doesn't seem to be a strict standard as to what to put there if I look at other Compatible products. 

Looking at Compatible products from Jakarta EE 9 and 9.1, most of them have a zip file as their download_url. That's what i'm going to use.

But yeah it's either a zip file or the same link as the Download link.

2022-05-17 18:22 UTC, linkfang commented on data/compatible_products.yml
> +          download_url: 'http://download.eclipse.org/jakartaee/platform/8/eclipse-jakartaeetck-8.0.2.zip'
> 
> Looking at Compatible products from Jakarta EE 9 and 9.1, most of them have a zip file as their download_url. That's what i'm going to use.

Yep, the product zip file will work for sure (e.g. Eclipse GlassFish 6.1). 
But the zip file you have for the download_url here is not the product zip file but a jakartaeetck zip file. So, I think it would be better if we use either the product zip file or the download link if it's not available/provided.

2022-05-17 18:38 UTC, linkfang approved these changes

2022-05-17 18:38 UTC, ericpoirier commented on data/compatible_products.yml
> +          download_url: 'http://download.eclipse.org/jakartaee/platform/8/eclipse-jakartaeetck-8.0.2.zip'
Ok I see, I put the same url as for the Download link since it was not provided.

2022-05-17 18:40 UTC, linkfang commented on data/compatible_products.yml
> +          download_url: 'http://download.eclipse.org/jakartaee/platform/8/eclipse-jakartaeetck-8.0.2.zip'
Cool!

2022-05-18 12:04 UTC, merged