feat: Update Wildfly to alpha5 on JEE core profile 10
jakartaee/jakarta.ee pull request #1549
Opened 2022-09-28 13:35 UTC by ZacharySabourin

Resolves https://github.com/jakartaee/jakarta.ee/issues/1548

2022-09-29 15:11 UTC, ZacharySabourin commented
+1 from Scott

2022-09-29 18:04 UTC, autumnfound commented
Do not merge until accepted as valid TCK results. PR looks good otherwise

2022-09-30 13:08 UTC, oliviergoulet5 requested changes

2022-09-30 13:08 UTC, oliviergoulet5 commented on data/compatible_products.yml
> +              compatibility: 'https://github.com/eclipse-ee4j/jakartaee-platform/issues/555'
The `compatibility` should be linked to the TCK test results public URL. For this one it would be [this](https://github.com/wildfly/certifications/blob/EE10/WildFly_27.0.0.Alpha5/jakarta-core-jdk17.adoc#jakarta-core-profile-1000-tck-java-se-17-results).

You need to change the one for SE 11 as well to whatever they linked in the other issue.

2022-10-13 17:51 UTC, ericpoirier approved these changes

2022-10-13 17:51 UTC, merged