Draft: Update committee lists
jakartaee/jakarta.ee pull request #1557
Opened 2022-10-05 14:00 UTC by oliviergoulet5

Resolves #1556

2022-10-05 14:36 UTC, chrisguindon commented
I've reach out to Netlify support to report that our Netlify previews are no longer working today when it was yesterday: https://github.com/jakartaee/jakarta.ee/pull/1555

2022-10-06 06:16 UTC, ivargrimstad commented on content/committees/specification/_index.md
>  * Marcelo Ancelmo - London Java Community - Elected Participant Member Representative, Martijn Verburg - alternate
I don't think Martijn is the alternate, but check with @TanjaObradovic

2022-10-06 06:16 UTC, ivargrimstad commented on content/committees/specification/_index.zh.md
>  * Marcelo Ancelmo - London Java Community - Elected Participant Member Representative, Martijn Verburg - alternate
Same comment as for the English version

2022-10-06 06:24 UTC, ivargrimstad requested changes
Replace Martijn Verburg with  Marcin Kruglik from LJC as Participant Member rep in steering committee. No alternates specified yet

2022-10-06 13:24 UTC, TanjaObradovic commented on content/committees/specification/_index.md
>  * Marcelo Ancelmo - London Java Community - Elected Participant Member Representative, Martijn Verburg - alternate
For the time being please keep Martijn.

2022-10-07 19:31 UTC, oliviergoulet5 commented
@ivargrimstad Updated to include Marcin Kruglik to the steering committee. Tanja provided Martjin Verburg as the alternate.

2022-10-08 05:51 UTC, ivargrimstad approved these changes

2022-10-11 12:01 UTC, merged