[zh]translate learn/starter,supporter,projects,release/10 & update/translate menu
jakartaee/jakarta.ee pull request #1950
Opened 2024-07-04 07:31 UTC by laliwa

translate learn/starter,supporter,projects,release/10
update/translate menu

2024-07-04 13:56 UTC, oliviergoulet5 requested changes
Aside from some things mentioned above, this PR looks really good!

2024-07-04 13:56 UTC, oliviergoulet5 commented on content/specifications/_index.md
We need to keep these index pages for /specifications. 

Same for the ZH and JA locales.

2024-07-04 13:56 UTC, oliviergoulet5 commented on layouts/shortcodes/pages/learn/starter_guides.html
This shortcode has been replaced with layouts/shortcodes/guides_list.html. You shouldn't need to re-add the starter_guides.html shortcode.

This was to make the shortcode more generic to be used for other types of guides such as specification guides.

2024-07-23 07:13 UTC, laliwa commented on layouts/shortcodes/pages/learn/starter_guides.html
Okay, got that, will notice that in the next commit.

2024-07-23 07:14 UTC, laliwa commented on content/specifications/_index.md
Thanks for that checking, fix missing files now.

2024-12-06 15:14 UTC, oliviergoulet5 approved these changes

2024-12-06 15:17 UTC, merged

2024-12-06 15:19 UTC, oliviergoulet5 commented
Thanks @laliwa !