add featured story and modify a little less
jakartaee/jakarta.ee pull request #914
Opened 2020-10-07 19:04 UTC by flora8984461

One of https://github.com/EclipseFdn/jquery-eclipsefdn-api/issues/16

Signed-off-by: Yi Liu <yi.liu@eclipse-foundation.org>

2020-10-07 19:05 UTC, flora8984461 commented on less/styles.less
> -    }
I am removing this because the text color is white on JakartaEE on light background, cannot see clearly

2020-10-08 11:45 UTC, ericpoirier approved these changes

2020-10-08 20:12 UTC, flora8984461 commented
https://github.com/EclipseFdn/ecdtools.eclipse.org/pull/58#issuecomment-705752389 same question

2020-10-13 18:48 UTC, chrisguindon requested changes
The featured story is showing in footer. This will require a patch to our base theme.

2020-10-13 19:30 UTC, merged