SEO Optimization: Meta Refresh #941
jakartaee/jakarta.ee pull request #946
Opened 2020-11-12 20:59 UTC by flora8984461

Fix #941 

Signed-off-by: Yi Liu <yi.liu@eclipse-foundation.org>

2020-11-12 21:43 UTC, flora8984461 commented
Pages to be updated:

- [ ] Home
   - seo_title
   - description
   - some contents (such as h1, h2, text change, etc)
- [ ] About
   - seo_title
   - description
   - some contents (such as h1, h2, text change, etc)
   - Need a new page to explain what jakarta ee is?
- [ ] Membership
   - seo_title
   - description
   - some contents (such as h1, h2, text change, etc)
- [ ] Connect
   - seo_title
   - description
   - some contents (such as h1, h2, text change, etc)
- [ ] Resources
   - seo_title
   - description
   - some contents (such as h1, h2, text change, etc)
- [ ] Compatible Products
   - seo_title
   - description
   - changed h2 h1 stuff
   - some contents (On Hold)
- [ ] Get Listed
   - seo_title
   - description
   - some contents (such as h1, h2, text change, etc)
- [ ] Release
   - seo_title
   - description
- [ ] Events
   - seo_title
   - description
   - some contents (such as h1, h2, text change, etc)
- [ ] FAQ
   - seo_title
   - description
   - some contents (such as h1, h2, text change, etc)
- [ ] News
   - seo_title
   - description
   - some contents (such as h1, h2, text change, etc)
- [ ] Newsletter
   - seo_title
   - description
   - some contents (such as h1, h2, text change, etc)
- [ ] Meeting Minutes
   - seo_title
   - description
   - some contents (such as h1, h2, text change, etc)

- [ ] Specifications
   - seo_title
   - description
   - some contents (such as h1, h2, text change, etc)
- [ ] Specifications/Platform
   - seo_title
   - description
   - some contents (such as h1, h2, text change, etc)
- [ ] Specifications/Platform Specs - Release 8
   - seo_title
   - description
- [ ] https://jakarta.ee/specifications/platform/8/platform-spec-8.html
   - seo_title
   - description

2020-11-13 19:36 UTC, flora8984461 commented
Just found another question I missed before:

Hope to confirm is this java? @chrisguindon 

![image](https://user-images.githubusercontent.com/39588094/99113551-76f8de00-25bd-11eb-953a-5fb5f195a115.png)

2020-11-20 21:14 UTC, chrisguindon requested changes

2020-11-20 21:14 UTC, chrisguindon commented on layouts/about/faq/section.html
> +{{ define "head-suffix" }}
My concern with this solution is that we are duplicating the content.

How about we create a data file to manage the questions and answers? 

I think this is is a really neat update and we should look at porting this back to hugo-solstice-theme once we are done!

2020-11-24 16:12 UTC, closed without merging